// <auto-generated />
using System;
using BookBuddyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBuddyAPI.Migrations
{
    [DbContext(typeof(BookBuddyGeneralDbContext))]
    [Migration("20250725012247_Notification and Buddy tables 0724")]
    partial class NotificationandBuddytables0724
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Buddy", b =>
                {
                    b.Property<Guid>("UserAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FriendsSince")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserAId", "UserBId");

                    b.HasIndex("UserBId");

                    b.HasIndex("UserId");

                    b.ToTable("Buddies");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.BuddyRequest", b =>
                {
                    b.Property<Guid>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActiveUserId", "PassiveUserId");

                    b.HasIndex("PassiveUserId");

                    b.ToTable("BuddyRequest");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookOfInterest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UserBook");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<Guid>("UsersWantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsersWantToReadId", "WantToReadId");

                    b.HasIndex("WantToReadId");

                    b.ToTable("BookUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("ReceivedBuddyRequestsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SentBuddyRequestsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceivedBuddyRequestsId", "SentBuddyRequestsId");

                    b.HasIndex("SentBuddyRequestsId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Buddy", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany("Buddies")
                        .HasForeignKey("UserId");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.BuddyRequest", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", "ActiveUser")
                        .WithMany("SentBuddyRequestsJoin")
                        .HasForeignKey("ActiveUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "PassiveUser")
                        .WithMany("ReceivedBuddyRequestsJoin")
                        .HasForeignKey("PassiveUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActiveUser");

                    b.Navigation("PassiveUser");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.Book", "Book")
                        .WithMany("UserBookJoin")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "User")
                        .WithMany("WantReadJoin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersWantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("WantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ReceivedBuddyRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SentBuddyRequestsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Navigation("UserBookJoin");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Navigation("Buddies");

                    b.Navigation("ReceivedBuddyRequestsJoin");

                    b.Navigation("SentBuddyRequestsJoin");

                    b.Navigation("WantReadJoin");
                });
#pragma warning restore 612, 618
        }
    }
}
