// <auto-generated />
using System;
using BookBuddyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBuddyAPI.Migrations
{
    [DbContext(typeof(BookBuddyGeneralDbContext))]
    [Migration("20250716231455_BuddyRequestJoin Migration7")]
    partial class BuddyRequestJoinMigration7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBuddyAPI.Models.DTO.BookDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookDTO");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.DTO.UserDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDTO");

                    b.HasData(
                        new
                        {
                            Id = new Guid("603e74b2-511a-431c-b9d5-1db379a0eb0e"),
                            CreatedAt = new DateTime(2025, 6, 23, 17, 40, 28, 901, DateTimeKind.Local).AddTicks(7489),
                            Email = "joshthewise57@gmail.com",
                            UserName = "HelioMoonWave Literati"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("603e74b2-512a-432c-b9d5-1db379a0eb0e"),
                            Author = "Leo Tolstoy",
                            Title = "War and Peace"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.BuddyRequestJoin", b =>
                {
                    b.Property<Guid>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PassiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActiveUserId", "PassiveUserId");

                    b.HasIndex("PassiveUserId");

                    b.ToTable("BuddyRequestJoin");

                    b.HasData(
                        new
                        {
                            ActiveUserId = new Guid("b8e244db-c0a5-440b-990f-50d65ac34add"),
                            PassiveUserId = new Guid("603e74b2-511a-431c-b9d5-1db379a0eb0e"),
                            DateAdded = new DateTime(2025, 6, 24, 17, 3, 28, 901, DateTimeKind.Local).AddTicks(7489),
                            Note = "Trying out adding Ogre as a new buddy request value"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UserBook");
                });

            modelBuilder.Entity("BookDTOUserDTO", b =>
                {
                    b.Property<Guid>("UsersWantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsersWantToReadId", "WantToReadId");

                    b.HasIndex("WantToReadId");

                    b.ToTable("BookDTOUserDTO");
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.Property<Guid>("UsersWantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WantToReadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsersWantToReadId", "WantToReadId");

                    b.HasIndex("WantToReadId");

                    b.ToTable("BookUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<Guid>("ReceivedBuddyRequestsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SentBuddyRequestsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceivedBuddyRequestsId", "SentBuddyRequestsId");

                    b.HasIndex("SentBuddyRequestsId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.BuddyRequestJoin", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", "ActiveUser")
                        .WithMany("SentBuddyRequestsJoin")
                        .HasForeignKey("ActiveUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "PassiveUser")
                        .WithMany("ReceivedBuddyRequestsJoin")
                        .HasForeignKey("PassiveUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ActiveUser");

                    b.Navigation("PassiveUser");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.Book", "Book")
                        .WithMany("UserBookJoin")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "User")
                        .WithMany("WantReadJoin")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookDTOUserDTO", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.DTO.UserDTO", null)
                        .WithMany()
                        .HasForeignKey("UsersWantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.DTO.BookDTO", null)
                        .WithMany()
                        .HasForeignKey("WantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookUser", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersWantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("WantToReadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ReceivedBuddyRequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("SentBuddyRequestsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Navigation("UserBookJoin");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Navigation("ReceivedBuddyRequestsJoin");

                    b.Navigation("SentBuddyRequestsJoin");

                    b.Navigation("WantReadJoin");
                });
#pragma warning restore 612, 618
        }
    }
}
