// <auto-generated />
using System;
using BookBuddyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBuddyAPI.Migrations
{
    [DbContext(typeof(BookBuddyGeneralDbContext))]
    partial class BookBuddyGeneralDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("603e74b2-512a-432c-b9d5-1db379a0eb0e"),
                            Author = "Leo Tolstoy",
                            Title = "War and Peace"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("603e74b2-511a-431c-b9d5-1db379a0eb0e"),
                            CreatedAt = new DateTime(2025, 6, 23, 17, 40, 28, 901, DateTimeKind.Local).AddTicks(7489),
                            Email = "joshthewise57@gmail.com",
                            UserName = "HelioMoonWave Literati"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("UserBook");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("603e74b2-511a-431c-b9d5-1db379a0eb0e"),
                            BookId = new Guid("603e74b2-512a-432c-b9d5-1db379a0eb0e"),
                            DateAdded = new DateTime(2025, 6, 24, 17, 3, 28, 901, DateTimeKind.Local).AddTicks(7489),
                            Note = "Trying out adding a want to read value"
                        });
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.UserBook", b =>
                {
                    b.HasOne("BookBuddyAPI.Models.Domain.Book", "Book")
                        .WithMany("UsersWantToRead")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookBuddyAPI.Models.Domain.User", "User")
                        .WithMany("WantToRead")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.Book", b =>
                {
                    b.Navigation("UsersWantToRead");
                });

            modelBuilder.Entity("BookBuddyAPI.Models.Domain.User", b =>
                {
                    b.Navigation("WantToRead");
                });
#pragma warning restore 612, 618
        }
    }
}
